# This is Home Assistant configuration. This goes into your configuration.yaml file (or packages folder if you have split your config)
# you need to provide your API key

weather:
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily

sensor:
  - platform: template
    sensors:
      today_min:
        value_template: "{{ state_attr('weather.dark_sky','forecast')[0].templow | default('0') }}"
        friendly_name: Today's maximal temperature
      today_max:
        value_template: "{{ state_attr('weather.dark_sky','forecast')[0].temperature | default('0') }}"
        friendly_name: Today's minimal temperature
      today_rain:
        value_template: "{{ state_attr('weather.dark_sky','forecast')[0].precipitation | default('0') }}"
        friendly_name: Today's rain forecast
      today_icon:
        value_template: >-
          {% if state_attr("weather.dark_sky","forecast")[0].condition =='clear-night' %}
            3
          {% elif state_attr("weather.dark_sky","forecast")[0].condition =='cloudy' %}
            4
          {% elif state_attr("weather.dark_sky","forecast")[0].condition =='fog' %}
            15
          {% elif state_attr("weather.dark_sky","forecast")[0].condition =='hail' %}
            5
          {% elif state_attr("weather.dark_sky","forecast")[0].condition =='lightning' %}
            12
          {% elif state_attr("weather.dark_sky","forecast")[0].condition =='lightning-rainy' %}
            16
          {% elif state_attr("weather.dark_sky","forecast")[0].condition =='partlycloudy' %}
            7
          {% elif state_attr("weather.dark_sky","forecast")[0].condition =='pouring' %}
            17
          {% elif state_attr("weather.dark_sky","forecast")[0].condition =='rainy' %}
            8
          {% elif state_attr("weather.dark_sky","forecast")[0].condition =='snowy' %}
            10
          {% elif state_attr("weather.dark_sky","forecast")[0].condition =='snowy-rainy' %}
            6
          {% elif state_attr("weather.dark_sky","forecast")[0].condition =='windy' %}
            13
          {% elif state_attr("weather.dark_sky","forecast")[0].condition =='windy-variant' %}
            13
          {% else %}
            11
          {% endif %}
        friendly_name: Today weather forecast
